### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by daivem** [Tuhinshubhra/CMSeeK#13]
`[!] No luck with headers... Continuing with source code
[!] Generator meta tag not found! (Procceeding with scan 2.2 of 2.2)
Traceback (most recent call last):
  File "cmseek.py", line 87, in <module>
    core.main_proc(site,cua)
  File "/root/soft/CMSeeK/cmseekdb/core.py", line 156, in main_proc
    cmseek.error("Couldn't detect cms... :( \n    Sorry master didn't mean to dissapoint but bye for now \n    Can't handle this much disappintment \n\n")
  File "/root/soft/CMSeeK/cmseekdb/basic.py", line 149, in error
    print(bold + red + "[\u274c] " + msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u274c' in position 10: ordinal not in range(128)
`

`/root/.pyenv/versions/3.6.6/bin/python3 cmseek.py`

pyenv 
python 3.6.6
ubuntu 16.04

**Comment by Tuhinshubhra** [comment]
looks like '❌' this charecter isn't supported...
