### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Kalimon12** [Tuhinshubhra/CMSeeK#16]
Traceback (most recent call last):
  File "cmseek.py", line 17, in <module>
    import cmseekdb.core as core
  File "/root/CMSeeK/cmseekdb/core.py", line 23, in <module>
    import cmseekdb.generator as generator
  File "/root/CMSeeK/cmseekdb/generator.py", line 31
    global ga, ga_content
    ^
SyntaxError: name 'ga' is assigned to before global declaration

**Comment by Coolncamp** [comment]
python3 cmseek.py
Traceback (most recent call last):
  File "cmseek.py", line 17, in <module>
    import cmseekdb.core as core
  File "/home/juju/CMSeeK/cmseekdb/core.py", line 23, in <module>
    import cmseekdb.generator as generator
  File "/home/juju/CMSeeK/cmseekdb/generator.py", line 31
    global ga, ga_content
    ^
SyntaxError: name 'ga' is assigned to before global declaration




Ubuntu Linux juju-VirtualBox 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Tuhinshubhra** [comment]
Fixed! please update your version of CMSeeK
