### ISSUE TITLE
A wierd error...

### ISSUE THREAD

**Issue by Kongledyret** [Tuhinshubhra/CMSeeK#18]
Python: 3.6.5 
Error: Traceback (most recent call last):
  File "cmseek.py", line 117, in <module>
    core.main_proc(site,cua)
  File "/root/CMSeeK/cmseekdb/core.py", line 101, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content)
  File "/root/CMSeeK/deepscans/core.py", line 14, in start
    joomscan.start(id, url, ua, ga, source)
  File "/root/CMSeeK/deepscans/joom/init.py", line 76, in start
    cmseek.result('Target: ',url)
  File "/root/CMSeeK/cmseekdb/basic.py", line 147, in result
    print(bold + fgreen + "[\u2714] " + stm + cln + msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 10: ordinal not in range(128)

**Comment by Tuhinshubhra** [comment]
I've applied a possible fix, can you try and confirm it works?

**Comment by Kongledyret** [comment]
That did the trick! Thanks!

**Comment by Tuhinshubhra** [comment]
Cool, Thank you for reporting the issue. Closing the issue, feel free to open a new one in case you face any other bugs / suggest changes.
