### ISSUE TITLE
Bruteforce Wordpress Traceback

### ISSUE THREAD

**Issue by mayankdebnath** [Tuhinshubhra/CMSeeK#2]
Traceback (most recent call last):leries
  File "cmseek.py", line 110, in <module>
    cms_brute()
  File "/root/CMSeeK/cmsbrute/wp.py", line 80, in start
    if passfound == '0':
UnboundLocalError: local variable 'passfound' referenced before assignment

**Comment by Tuhinshubhra** [comment]
Fixed, Please update your version of CMSeeK.
Thank you for reporting.
