### ISSUE TITLE
some wp sites error

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#84]
Hello, after some time i continue with scanning and found some issues. Scanning many domains ending with Error status. In Results is in affected domain an empty .json file

**bikeandroll.sk**
Traceback (most recent call last):
  File "cmseek.py", line 128, in <module>
    core.main_proc(target,cua)
  File "/root/CMSeeK/cmseekdb/core.py", line 132, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content, detection_method, headers)
  File "/root/CMSeeK/deepscans/core.py", line 10, in start
    wpscan.start(id, url, ua, ga, source, detection_method)
  File "/root/CMSeeK/deepscans/wp/init.py", line 136, in start
    sresult.target(url)
  File "/root/CMSeeK/cmseekdb/result.py", line 12, in target
    print(' \u250f\u2501Target: ' + cmseek.bold + cmseek.red + target + cmseek.cln)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

**bikeangel.sk**
Traceback (most recent call last):
  File "cmseek.py", line 128, in <module>
    core.main_proc(target,cua)
  File "/root/CMSeeK/cmseekdb/core.py", line 132, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content, detection_method, headers)
  File "/root/CMSeeK/deepscans/core.py", line 10, in start
    wpscan.start(id, url, ua, ga, source, detection_method)
  File "/root/CMSeeK/deepscans/wp/init.py", line 136, in start
    sresult.target(url)
  File "/root/CMSeeK/cmseekdb/result.py", line 12, in target
    print(' \u250f\u2501Target: ' + cmseek.bold + cmseek.red + target + cmseek.cln)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

Can you check and find where is problem ? Or, if it is very time compsumpting, just make script to continue scanning.

**Comment by Tuhinshubhra** [comment]
this issue is not related to wordpress, rather the result as a whole. I'll fix it soon.

**Comment by masterwebsk** [comment]
Hello, any news ? 

I tried to new install (git clone cmseek) on centos 7.7 with python3 install + upgrade to latest pip, but the same result...

[+]  CMS Scan Results  [+]

Traceback (most recent call last):
  File "cmseek.py", line 106, in <module>
    core.main_proc(target,cua)
  File "/home/xxx/CMSeeK/cmseekdb/core.py", line 143, in main_proc
    result.target(site)
  File "/home/xxx/CMSeeK/cmseekdb/result.py", line 12, in target
    print(' \u250f\u2501Target: ' + cmseek.bold + cmseek.red + target + cmseek.cln)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
