### ISSUE TITLE
Problem with wpvdbres

### ISSUE THREAD

**Issue by ThOhT** [Tuhinshubhra/CMSeeK#9]
I was trying option 1 on a WordPress website and caught this error below:

[â] Detected CMS: WordPress
[â] CMS URL: https://wordpress.org
Traceback (most recent call last):
  File "cmseek.py", line 63, in <module>
    core.main_proc(site,cua)
  File "/home/diego/Programas/CMSeeK/cmseekdb/core.py", line 156, in main_proc
    advanced.deep(c22[1], site, cua, '0', scode)
  File "/home/diego/Programas/CMSeeK/cmseekdb/dnv.py", line 186, in deep
    if wpvdbres == '1':
UnboundLocalError: local variable 'wpvdbres' referenced before assignment

**Comment by Tuhinshubhra** [comment]
Please provide the following informations:
1. Target url
2. Your OS
3. CMSeeK Version

**Comment by Tuhinshubhra** [comment]
Closing the issue, feel free to open with all the sufficient information!
